name: build
on: [ push ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: sync dependencies
      shell: bash
      run: |
        pip3 install pipenv
        pipenv sync
    - name: run build script
      shell: bash
      run: pipenv run python -m scripts build